export const teachers = {
    RKU: 'Dr. Rajiv Kumar',
    SHR: 'Dr. Shruti Jain',
    SWT: 'Dr. Shweta Pandit',
    SLD: 'Dr. Sunil Datt Sharma',
    NFK: 'Dr. Nafis uddin Khan',
    HSL: 'Dr. Harsh Sohal',
    EMP: 'Dr. Emjee Puthooran',
    VKB: 'Dr. Vikas Baghel',
    NTJ: 'Dr. Nishant Jain',
    SRU: 'Dr. Salman Raju Talluri',
    NVN: 'Dr. Naveen Jaglan',
    PDG: 'Dr. Pardeep Garg',
    ALK: 'Dr. Alok Kumar',
    MSD: 'Mr. Munish Sud',
    PRG: 'Ms. Pragya Gupta',
    VSG: 'Dr. Vivek Sehgal',
    PKR: 'Dr. Pardeep Kumar',
    PKG: 'Dr. Pradeep Kumar Gupta',
    RJM: 'Dr. Rajni Mohna',
    RBT: 'Dr. Ravindara Bhatt',
    YGL: 'Dr. Yugal Kumar',
    ARV: 'Mr. Arvind Kumar',
    AVA: 'Dr. Amol Vasudeva',
    PMI: 'Dr. Praveen Modi',
    RIV: 'Dr. Ruchi Verma',
    EGA: 'Dr. Ekta Gandotra',
    AKJ: 'Dr. Amit Kumar Jakhar',
    HJL: 'Dr. Himanshu Jindal',
    HRI: 'Dr. Hari Singh',
    JAG: 'Dr. Jagpreet Singh Sandhu',
    MBI: 'Dr. Monika Bharti',
    PTK: 'Mr. Prateek Thakral',
    AMN: 'Dr. Aman Sharma',
    RKI: 'Dr. Rakesh Kanji',
    DGA: 'Dr. Deepak Gupta',
    VKS: 'Dr. Vipul Kr. Sharma',
    PDN: 'Dr. Pankaj Dhiman',
    SGL: 'Dr. Shubham Goyal',
    SSA: 'Dr. Simran Setia',
    NSA: 'Dr. Nancy Singla',
    NTS: 'Dr. Nishant Sharma',
    ABS: 'Dr. Abhilasha Sharma',
    KLK: 'Dr. Kushal Kanwar',
    DHA: 'Dr. Diksha Hooda',
    NF1: 'CS Faculty-1',
    NF2: 'CS Faculty-2',
    NF3: 'CS Faculty-3',
    NF4: 'CS Faculty-4',
    NF5: 'CS Faculty-5',
    NF6: 'CS Faculty-6',
    NF7: 'CS Faculty-7',
    NF8: 'CS Faculty-8',
    ASR: 'Prof. Ashish Kumar',
    AKG: 'Prof. Ashok Kumar Gupta',
    CPG: 'Mr. Chandrapal Gautam',
    SUB: 'Dr. Saurabh Rawat',
    LAB: 'Dr. Saurav SUV CL9',
    NJP: 'Mr. Niraj Singh Parihar',
    KKR: 'Mr. Kaushal Kumar',
    ADP: 'Dr. Amardeep',
    RRA: 'Dr. Rishi Rana',
    TNM: 'Dr. Tanmay',
    ABJ: 'Mr. Akash Bhardwaj',
    SGS: 'Dr. Sugandha Singh',
    SDS: 'Prof. Sudhir Syal',
    JAS: 'Dr. Jata Shankar',
    AKT: 'Dr. Anil Kant',
    RST: 'Dr. Rahul Shrivastava',
    TTS: 'Dr. Tiratha Raj Singh',
    HSD: 'Dr. Hemant Sood',
    PNS: 'Dr. Poonam Sharma',
    JTV: 'Dr. Jitendraa Vashistt',
    GAI: 'Dr. Garlapati Vijay Kumar',
    SBS: 'Dr. Saurabh Bansal',
    ABH: 'Dr. Abhishek Chaudhary',
    AKN: 'Dr. Ashok Nadda',
    GPL: 'Dr. Gopal Singh Bisht',
    UDB: 'Dr. Uday Banu M',
    RJK: 'Dr. Raj Kumar',
    SML: 'Dr. Shikha Mittal',
    TYN: 'Dr. Tyson',
    ANU: 'Dr. Anupriya Kaur',
    ASA: 'Dr. Amit Srivastava',
    TNS: 'Dr. Tanu Shrma',
    TGM: 'Ms. Triambica Gautam',
    NJL: 'Dr. Neena Jindal',
    DLR: 'Dr. Deler Singh',
    HSS1: 'Dr. Atul Kumar Singh',
    HSS2: 'Dr. Ranjith Kallyani',
    HSS3: 'Dr. Bilal Khan',
    PBB: 'Prof. P.B. Barman',
    SKK: 'Prof. Sunil K. Khah',
    VSA: 'Dr. Vineet Sharma',
    HAZ: 'Dr. S.K.Hazra',
    RRS: 'Dr. Ragni Raj Singh',
    SKT: 'Dr. Sanjiv Kumar Tiwari',
    SBA: 'Dr. Santu Baidya',
    HSR: 'Dr. Haresh A. Raval',
    KAS: 'Prof. Karanjeet Singh',
    RAD: 'Dr. R. S. Raja Durai',
    RKB: 'Dr. Rakesh Bajaj',
    BKP: 'Dr. Bhupendra Kumar Pathak',
    NKT: 'Dr. Neel Kanth',
    PKP: 'Dr. Pradeep Kumar Pandey',
    SST: 'Dr. Saurabh Srivastava',
    MDS: 'Dr. Mandeep Singh'
}
